In [25]:
import numpy as np
import matplotlib.pyplot as plt
data = np.loadtxt('./datasets/example.txt',delimiter=' ')
X = np.array(data)
y = np.array([0,0,0,1,1,1,1,2,2])
print(data)

#plt.matshow(X) 
#plt.show()


[[  1.2   3.7  12.    9.    5. ]
 [  1.3   3.5  11.    8.    4. ]
 [  1.2   5.   12.    8.    5. ]
 [  3.    5.    5.    8.    5. ]
 [  4.2   5.2   8.4   4.5   5.3]
 [  4.1   6.2   8.7   4.2   5.6]
 [  3.6   6.4   7.3   4.7   5.6]
 [ 11.6   6.2  12.3   4.8   5.6]
 [ 11.8   9.5  11.3   4.6   5.9]]


In [14]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
svc.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
svc.predict([[2.1, 4.2, 12, 7.5, 5]])

array([0])